// GENERATED by scripts/sync-contract.mjs — do not edit by hand.
//
// The fingerprint of the node-bill contract vendored into this package, using
// the same digest as `sync-contract.mjs` and as node-bill's own
// `GET /health/contract`. Comparing the two answers the only question that
// matters after pinning an SDK version: does the deployment I am calling still
// speak the contract I compiled against?
//
// `test/diagnose.test.ts` recomputes this from `src/generated` on every
// `npm run check`, so a hand-edited contract cannot leave the constant stale.
export const CONTRACT_SHA256 = "efb28779fe6a21b5b16b0f6c1d055ec3796d5b0402c7fa34b6c873de32973237";
