// GENERATED by scripts/sync-contract.mjs — do not edit by hand.
//
// The fingerprint of the node-bill contract vendored into this package, using
// the same digest as `sync-contract.mjs` and as node-bill's own
// `GET /health/contract`. Comparing the two answers the only question that
// matters after pinning an SDK version: does the deployment I am calling still
// speak the contract I compiled against?
//
// `test/diagnose.test.ts` recomputes this from `src/generated` on every
// `npm run check`, so a hand-edited contract cannot leave the constant stale.
export const CONTRACT_SHA256 = "53b80b8a40f3d045fc8719412613e7063b94ff649408c53650ff7807da877801";
