// GENERATED by scripts/sync-contract.mjs — do not edit by hand.
//
// The fingerprint of the node-bill contract vendored into this package, using
// the same digest as `sync-contract.mjs` and as node-bill's own
// `GET /health/contract`. Comparing the two answers the only question that
// matters after pinning an SDK version: does the deployment I am calling still
// speak the contract I compiled against?
//
// `test/diagnose.test.ts` recomputes this from `src/generated` on every
// `npm run check`, so a hand-edited contract cannot leave the constant stale.
export const CONTRACT_SHA256 = "bfd85f17c2aa38bf82c759d02eefaecde34d402f7704d074e5fcdc8cb35c3990";
